pull_request_rules:
  - name: automatic merge and delete on CI success
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
      - status-success=continuous-integration/appveyor/pr
      - status-success=continuous-integration/appveyor/branch
      - label=merge when passing
      - label=small fix
    actions:
      merge:
        method: merge
      delete_head_branch: {}


  - name: automatic merge and keep on CI success
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
      - status-success=continuous-integration/appveyor/pr
      - status-success=continuous-integration/appveyor/branch
      - label=merge when passing
    actions:
      merge:
        method: merge

  - name: comment on PR
    conditions:
      - author != @mcguinlu
    actions:
      comment: Thanks for your PR - I'll review it as soon as possible!
